# Generated by Django 5.2.7 on 2025-11-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0004_auto_20251106_1825"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
