# Generated by Django 5.2.8 on 2025-11-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_name', models.CharField(max_length=100)),
                ('supply_code', models.CharField(max_length=240, unique=True)),
                ('supply_unit', models.CharField(max_length=50)),
                ('supply_initial_stock', models.IntegerField(default=0)),
                ('supply_input', models.IntegerField(default=0)),
                ('supply_output', models.IntegerField(default=0)),
                ('supply_total', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['supply_name'],
                'managed': False,
            },
        ),
    ]
