# Generated by Django 5.2.8 on 2025-11-20 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False, 'ordering': ['supply_name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
