# Generated by Django 5.2.8 on 2025-11-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_merge_20240531_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supply_total',
        ),
        migrations.AlterField(
            model_name='product',
            name='supply_initial_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='supply_input',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='supply_output',
            field=models.IntegerField(default=0),
        ),
    ]
